import NavBar from "../components/NavBar";
import "./globals.css";

export const metadata = {
  title: "Meet",
  description: "Generated by Syntax squad",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body

      >

        <NavBar />

        {children}
      </body>
    </html>
  );
}
